version: "3.1"

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: student_meals
      POSTGRES_USER: martin
      POSTGRES_PASSWORD: 031291778ab041d470564b57e3e60ddc43a66fc99e043d60906db79b46fa5fe7
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  data: